### ISSUE TITLE
`Error: writeStatic has been removed. Please ensure you are using the latest version of svelte-adapter-github`

### ISSUE THREAD

**Issue by jerrygreen** [malynium/svelte-adapter-github#2]
This error appears when I try to build my project with most currently recent versions:
- `"@sveltejs/kit": "1.0.0-next.405",`
- `"svelte-adapter-github": "0.0.1-next.0",`

When I try to use older `@sveltejs/kit`, I bump into this another issue:
- [builder.prerender() has been removed](https://github.com/malynium/svelte-adapter-github/issues/1)

Therefore I need to downgrade my `@sveltejs/kit` so much, that everything else just breaks up: and consecutively I need to downgrade almost everything to who knows which version, in order to find this short period of time when all this stack worked, for building SveltKit project for Github.

**Comment by jerrygreen** [comment]
More info about breaking changes:

- [What's new in Svelte: August 2022](https://svelte.dev/blog/whats-new-in-svelte-august-2022)

It seems they removed `writeStatic` at Jul 19 in here: https://github.com/sveltejs/kit/pull/5618

**Comment by jerrygreen** [comment]
Btw I just tried to use all the old versions, so `svelte-adapter-github` works again, but it seems it does not generate all the needed pages, like `about.html`, `blog.html`, etc. Only `index.html`... It's a false adapter: it never worked.

![image](https://user-images.githubusercontent.com/13215662/185288892-a1183e9d-7614-4e03-a067-75ef69d05bb1.png)

**Comment by j4w8n** [comment]
Thank you.

With the upcoming changes on https://github.com/sveltejs/kit/pull/5845, I'm starting to think I need to deprecate this package. I originally just copied the code from sveltekit's static adapter, then modified it a bit for use with Github.

If I do continue it, I need to make some changes so I can merge updates from the official adapter-static and make some tweaks so this adapter will work with newer versions of sveltekit.

**Comment by jerrygreen** [comment]
Actually, yes, `adapter-static` seems to be enough. I'm using it currently, it seems to work without an issue.

**Comment by j4w8n** [comment]
Ok, I finally found some time to get this straightened out. The latest version should be good, but since you're using the official `adapter-static` I'll close this issue.
